### ISSUE TITLE
Hexa color

### ISSUE THREAD

**Issue by lackooka** [kiranhart/ItemNameTags#1]
Hi, I want to rename my item with hexa colors and here is the result: 
![image](https://user-images.githubusercontent.com/83063334/167125646-e5ebf229-140a-4efb-8a6b-3b11ad5db895.png)
The hexa code is here: 
&#ff0000C&#ff1200o&#ff2400n&#ff3600f&#ff4800l&#ff5900a&#ff6b00g&#ff7d00r&#ff8f00a&#ffa100n&#ffa800t &#ffaf00F&#ffb500l&#ffbc00a&#ffc300m&#ffca00e &#ffd000B&#ffd700o&#ffde00w
The "&" symbol is not removed in here I don't know why.

**Comment by kiranhart** [comment]
you can remove the & and from the hex codes, ex #ff0000C#ff1200o#ff2400n#ff3600f#ff4800l#ff5900a#ff6b00g#ff7d00r#ff8f00a#ffa100n#ffa800t #ffaf00F#ffb500l#ffbc00a#ffc300m#ffca00e #ffd000B#ffd700o#ffde00w
